services:
  proxy-rotator:
    image: proxy-rotator:latest
    container_name: proxy-rotator
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped